### ISSUE TITLE
Command `toggleBookmark` fails when  saveBookmarksInProject is true

### ISSUE THREAD

**Issue by JeroenBos** [alefragnani/vscode-numbered-bookmarks#69]
I received the following error when toggling a bookmark as a vscode popup:

```
Running the contributed command: 
'numberedBookmarks.toggleBookmark1' failed.
```

The reason is because the file opened at the moment was outside of the project, and I have 
`numberedBookmarks.saveBookmarksInProject` set to true. 

I agree that this should be an error, however the message could be more specific, like _Can't create bookmark because this file is outside of the current project and  "saveBookmarksInProject" is true_ or something.

My point is that unawareness of this settings being true can stump you as to why the command fails.

I would also agree that this issue is nitpicky. I like your extension!

**Comment by alefragnani** [comment]
Hi @JeroenBos ,

It should work even if the file is outside the project (at least it was designed this way). Something/somewhere is not taking care as desired 😞 .

As you can se in `.vscode/numbered-bookmarks.json` file, the files _inside the projects_ receive a `"$ROOTPATH$` prefix. The _outsiders_ shouldn't have this but instead, its whole path. 

I've used the same initial concepts from my other [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) extension, which works just fine. Their codes are no shared, but I'm working on syncing, specially to improve the Numbered Bookmarks with features that only the Bookmarks extension provides today.

Hope this helps.

**Comment by nearwood** [comment]
I get this error if that setting is true, but on any file within my project. If I close and re-open the file, or even load another file in a tab and then switch back to that tab the bookmark was actually created.

**Comment by keyboardpartner** [comment]
HI,

same problem here. When trying to set a bookmark, Extension Host issues:

`[2021-01-30 18:30:59.022] [exthost] [error] TypeError: Cannot read property 'uri' of undefined
	at i.zip (c:\Users\Carsten\.vscode\extensions\alefragnani.numbered-bookmarks-7.3.0\dist\extension.js:1:29192)
	at Object.o.saveBookmarks (c:\Users\Carsten\.vscode\extensions\alefragnani.numbered-bookmarks-7.3.0\dist\extension.js:1:33971)
	at x (c:\Users\Carsten\.vscode\extensions\alefragnani.numbered-bookmarks-7.3.0\dist\extension.js:1:21057)
	at C (c:\Users\Carsten\.vscode\extensions\alefragnani.numbered-bookmarks-7.3.0\dist\extension.js:1:21517)
	at c:\Users\Carsten\.vscode\extensions\alefragnani.numbered-bookmarks-7.3.0\dist\extension.js:1:20662
	at _executeContributedCommand (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:753)
	at _.$executeContributedCommand (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:700:104)
	at g._doInvokeHandler (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:926)
	at g._invokeHandler (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:618)
	at g._receiveRequest (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:875:252)
	at g._receiveOneMessage (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:874:6)
	at c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:872:136
	at l.fire (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:601)
	at c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1066:179
	at l.fire (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:601)
	at t.PersistentProtocol._receiveMessage (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:629)
	at c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:708
	at l.fire (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at p.acceptChunk (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:989)
	at c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:341
	at Socket.t (c:\Users\Carsten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:276)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23) numberedBookmarks.toggleBookmark4
`
Maybe this helps. As it worked well a while ago, I really appreciate the bookmark extension.

**Comment by keyboardpartner** [comment]
I just unistalled NumberedBookmarks **and removed folder "alefragnani.numbered-bookmarks-7.3.0"**, deleted line in .obsolete and re-installed it. Now it works again.

**Comment by alefragnani** [comment]
Hi @keyboardpartner ,

Which kind of file (file extension) and project (single folder, multi-root workspace, remotes) were you using when the error appeared?
